# Generated by Django 4.2.16 on 2024-12-15 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adminapp', '0002_doctor_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=255)),
                ('age', models.PositiveIntegerField()),
                ('issue', models.TextField()),
                ('diagnosis', models.TextField()),
                ('medicines', models.TextField()),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.doctor')),
            ],
        ),
    ]
